Logsign Documentation
=====================
:toc: left
:numbered:


Introduction
------------

=== About Logsign

=== What is Logsign

=== What is New in Logsign Version 4

Installation
------------

How to install Logsign. link:installation.html[here]

=== Hyper-V

=== Vmware ESX

=== PC or Server

Basic Operations and Settings
-----------------------------

=== Mail Settings link:Mail.html[here]

=== SMS Settings link:SMS.html[here]

=== License Control link:License_control.html[here]

Data Collection
---------------

=== Syslog

=== WMI

=== Agent

=== File Share

=== Log Capture Tool

Ready Integrations
------------------

=== Microsoft Windows

=== Microsoft Exchange

=== Microsoft DHCP

=== Microsoft IIS

=== Sonicwall

=== Fortinet

=== PaloAlto

=== Checkpoint

=== Apache

Reporting
---------

=== Reporting Overview

=== Templates

==== Count

==== Group Report

==== Grouped Plus Report

==== Map

=== Default Reports

=== Report Scheduling

=== PDF and Excel Reporting

=== Create New Report

=== Modify Reports

=== Report Categories

=== Report Profiles

Search
------

=== Search Overview

=== Search Basics

=== Search Language

=== Search Analysis

Dashboards
----------

=== Overview

=== Widgets

=== Dashboard Wizard

Alert and Correlation
---------------------

=== Overview

=== Default Alert Rules

=== Templates

Delegation
----------

=== Profiling Overview

=== Interface

=== Report Delegation

=== Alert Delegation

Data Policy Manager
-------------------

=== Event Filtering

=== Redundancy

=== Indexing

=== Raw Data

Cluster and HA
--------------

Reference
---------

=== Smart Fields

=== Event Classification

=== Integrated Device Categorization

=== Default Reports

=== Default Alerts

=== System Requirement

=== Disk Planning

=== Capacity Planning

=== Contacting Customer Support

=== Licensing
